import type { Metadata } from "next";
import "./globals.css";

import { Poiret_One } from 'next/font/google';
const inter = Poiret_One({
  subsets: ['latin'], // Optional: Choose subsets
  weight: '400', // Optional: Choose font weights
  variable: '--font-inter', // Optional: Use CSS variable
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${inter.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
